// <auto-generated />
using System;
using CampTravelGear.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampTravelGear.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821202209_UpdateUserSeedData1")]
    partial class UpdateUserSeedData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampTravelGear.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-admin-001",
                            Email = "admin@barrameru.com",
                            EmailConfirmed = true,
                            FullName = "Admin Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BARRAMERU.COM",
                            NormalizedUserName = "ADMIN@BARRAMERU.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdaqL9mVLSYIYDQnf3VbN26q7GMI+7eZ1KJyWghZois4i24uitPbuHClLflhAdeGA==",
                            PhoneNumber = "+1 (555) 019-2834",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-admin-001",
                            TwoFactorEnabled = false,
                            UserName = "admin@barrameru.com"
                        },
                        new
                        {
                            Id = "user-cust-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-john-001",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FullName = "John Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 342-8901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-john-001",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "user-cust-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-sara-002",
                            Email = "sara.helvey@example.com",
                            EmailConfirmed = true,
                            FullName = "Sara G. Helvey",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.HELVEY@EXAMPLE.COM",
                            NormalizedUserName = "SARA.HELVEY@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 781-4329",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-sara-002",
                            TwoFactorEnabled = false,
                            UserName = "sara.helvey@example.com"
                        },
                        new
                        {
                            Id = "user-cust-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-alex-003",
                            Email = "alex.h@example.com",
                            EmailConfirmed = true,
                            FullName = "Alex Hunter",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.H@EXAMPLE.COM",
                            NormalizedUserName = "ALEX.H@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 629-1145",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-alex-003",
                            TwoFactorEnabled = false,
                            UserName = "alex.h@example.com"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Denver",
                            FullAddress = "124 Mountain Trail Rd, Apt 4B",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            City = "Seattle",
                            FullAddress = "582 Forest Pine Way",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            City = "Portland",
                            FullAddress = "910 Alpine Ridge Ave",
                            UserId = "user-cust-003"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "user-cust-001"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 2,
                            CartId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 3,
                            CartId = 1,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 140.00m
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Bags & Pack"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Tent & Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Camp Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Knives & Tools"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Climbing & Hiking"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAt = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            TotalAmount = 270.00m,
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAt = new DateTime(2026, 8, 18, 9, 15, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 18, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Processing",
                            TotalAmount = 185.00m,
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CreatedAt = new DateTime(2026, 8, 19, 16, 45, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 19, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            TotalAmount = 85.00m,
                            UserId = "user-cust-003"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 1,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 140.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 3,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 25.00m
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 270.00m,
                            OrderId = 1,
                            PaidAt = new DateTime(2026, 8, 10, 14, 32, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            Status = "Completed",
                            TransactionId = "TXN-849201"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 185.00m,
                            OrderId = 2,
                            PaidAt = new DateTime(2026, 8, 18, 9, 16, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "PayPal",
                            Status = "Completed",
                            TransactionId = "TXN-739102"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 85.00m,
                            OrderId = 3,
                            PaymentMethod = "Credit Card",
                            Status = "Pending",
                            TransactionId = "TXN-109483"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact aluminum lightweight folding camp stool for hiking trails and campsite relaxation.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Black Folding Stool",
                            Price = 45.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Double-layer waterproof 3-person dome camping tent with high-strength fiberglass poles and rainfly.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yellow 3-Person Tent",
                            Price = 65.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable self-inflating sleeping pad with integrated air pillow and moisture barrier.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Inflatable Camping Bed",
                            Price = 35.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Closed-cell foam moisture-proof ground sleeping pad for rugged outdoor adventures.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Orange Ground Camping Mat",
                            Price = 20.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-grade stainless steel multi-tool tactical folding pocket knife with secure locking mechanism.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Multi-Function Folding Knife",
                            Price = 25.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1000-lumen ultra-bright rechargeable waterproof tactical torch with zoomable beam.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tactical LED Flashlight",
                            Price = 50.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-definition compact roof prism binoculars with multi-coated anti-reflective lenses.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Black HD Binoculars 10x42",
                            Price = 65.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy-duty metal sighting navigation compass with fluorescent dial and clinometer.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Military Navigation Compass",
                            Price = 50.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Heavy-duty ergonomic internal frame mountain hiking backpack with rain cover and hydration port.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Trekking Expedition Backpack 65L",
                            Price = 150.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Waterproof full-grain leather hiking boots with high-traction Vibram rubber outsoles.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Brown Ankle-High Hiking Boots",
                            Price = 125.00m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Double-wall vacuum insulated stainless steel canteen keeping drinks hot for 12h or cold for 24h.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Insulated Metal Water Bottle 1L",
                            Price = 60.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Foldable stainless steel tabletop barbecue grill for backcountry cooking and tailgating.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Portable Camp Charcoal Grill",
                            Price = 100.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "9.8mm dynamic UIAA certified climbing rope with dry treatment for alpine ascents.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dynamic Climbing Ropes 60m",
                            Price = 80.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rugged military camo multi-compartment tactical pack with MOLLE webbing and padded harness.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Camouflage Tactical Backpack 50L",
                            Price = 140.00m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/top-view-of-travel-equipment-for-a-mountain-trip-e1664201262219.jpg",
                            IsMain = true,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/orange-tourist-tent-illuminated-from-inside-stands-in-mountains-above-clouds.jpg",
                            IsMain = true,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/camping-in-steppe.jpg",
                            IsMain = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/sandy-field-in-desert-of-egypt.jpg",
                            IsMain = true,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/43.jpg",
                            IsMain = true,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/panoramic-shot-of-two-young-tourists-looking-at-geographic-map-on-grey-background-e1664119398628.jpg",
                            IsMain = true,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/high-angle-view-of-confident-couple-climbing-mountain-e1664201089286.jpg",
                            IsMain = true,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/tourist-sitting-phu-sub-lek-viewpoint-sunset-lopburi-thailand-e1664089245105.jpg",
                            IsMain = true,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/blue-hiking-backpack-with-fitness-mat-isolated-on-2021-09-03-13-40-43-utc-1.jpg",
                            IsMain = true,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/tourist-with-a-backpack-against-the-sky-panorama.jpg",
                            IsMain = true,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/spending-time-by-the-campfire.jpg",
                            IsMain = true,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/paddling-kayaker-on-the-scenic-lake.jpg",
                            IsMain = true,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/high-angle-view-of-confident-couple-climbing-mountain-e1664201089286.jpg",
                            IsMain = true,
                            ProductId = 13
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/group-of-friends-with-backpacks-doing-trekking-excursion-on-mountain.jpg",
                            IsMain = true,
                            ProductId = 14
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedAt = new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "Excellent camping tent, set up took 5 minutes and withstands wind easily.",
                            CreatedAt = new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 5,
                            Status = "Accepted",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Incredible build quality and very comfortable back padding for multi-day treks.",
                            CreatedAt = new DateTime(2026, 8, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 9,
                            Rating = 4,
                            Status = "Pending",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Arrived with a slight scratch on the outer lens cap.",
                            CreatedAt = new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Rating = 2,
                            Status = "Rejected",
                            UserId = "user-cust-003"
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Super warm down sleeping bag for sub-zero mountain nights. Highly recommended!",
                            CreatedAt = new DateTime(2026, 8, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 14,
                            Rating = 5,
                            Status = "Pending",
                            UserId = "user-cust-001"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedAt = new DateTime(2026, 7, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Content = "We've seen amazing results already. Barrameru should be nominated for outdoor brand of the year. Great customer service!",
                            CreatedAt = new DateTime(2026, 7, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sara G. Helvey",
                            Status = "Accepted",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The best camping gear store I have ever used. Fast delivery and authentic rugged equipment.",
                            CreatedAt = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "John Doe",
                            Status = "Pending",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Spam test message or irrelevant feedback.",
                            CreatedAt = new DateTime(2026, 7, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alex Hunter",
                            Status = "Rejected",
                            UserId = "user-cust-003"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = "user-cust-001"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2026, 8, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            WishlistId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2026, 8, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 9,
                            WishlistId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-001",
                            ConcurrencyStamp = "role-admin-stamp",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-customer-002",
                            ConcurrencyStamp = "role-customer-stamp",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-001",
                            RoleId = "role-admin-001"
                        },
                        new
                        {
                            UserId = "user-cust-001",
                            RoleId = "role-customer-002"
                        },
                        new
                        {
                            UserId = "user-cust-002",
                            RoleId = "role-customer-002"
                        },
                        new
                        {
                            UserId = "user-cust-003",
                            RoleId = "role-customer-002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CampTravelGear.Models.Address", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.CartItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.HasOne("CampTravelGear.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.OrderItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Payment", b =>
                {
                    b.HasOne("CampTravelGear.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.HasOne("CampTravelGear.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CampTravelGear.Models.ProductImage", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Review", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Testimonial", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.WishlistItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CampTravelGear.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
