// <auto-generated />
using System;
using CampTravelGear.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampTravelGear.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampTravelGear.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "user-admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-admin-001",
                            Email = "admin@barrameru.com",
                            EmailConfirmed = true,
                            FullName = "Rahhala Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BARRAMERU.COM",
                            NormalizedUserName = "ADMIN@BARRAMERU.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEdaqL9mVLSYIYDQnf3VbN26q7GMI+7eZ1KJyWghZois4i24uitPbuHClLflhAdeGA==",
                            PhoneNumber = "+962 6 500 2026",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-admin-001",
                            TwoFactorEnabled = false,
                            UserName = "admin@barrameru.com"
                        },
                        new
                        {
                            Id = "user-cust-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-john-001",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FullName = "John Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 342-8901",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-john-001",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = "user-cust-002",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-sara-002",
                            Email = "sara.helvey@example.com",
                            EmailConfirmed = true,
                            FullName = "Sara G. Helvey",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.HELVEY@EXAMPLE.COM",
                            NormalizedUserName = "SARA.HELVEY@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 781-4329",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-sara-002",
                            TwoFactorEnabled = false,
                            UserName = "sara.helvey@example.com"
                        },
                        new
                        {
                            Id = "user-cust-003",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-alex-003",
                            Email = "alex.h@example.com",
                            EmailConfirmed = true,
                            FullName = "Alex Hunter",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALEX.H@EXAMPLE.COM",
                            NormalizedUserName = "ALEX.H@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+1 (555) 629-1145",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-alex-003",
                            TwoFactorEnabled = false,
                            UserName = "alex.h@example.com"
                        },
                        new
                        {
                            Id = "user-cust-004",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "con-stamp-omar-004",
                            Email = "omar.khalil@example.com",
                            EmailConfirmed = true,
                            FullName = "Omar Al-Khalil",
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.KHALIL@EXAMPLE.COM",
                            NormalizedUserName = "OMAR.KHALIL@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPvH9DFxtV1m7CiKbFG7DczGEaLFQzYgi5Ckg0OVEzpmEsDORBDjImwoH6IuqeZohA==",
                            PhoneNumber = "+962 7 9876 5432",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "sec-stamp-omar-004",
                            TwoFactorEnabled = false,
                            UserName = "omar.khalil@example.com"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Denver",
                            FullAddress = "124 Mountain Trail Rd, Apt 4B",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            City = "Seattle",
                            FullAddress = "582 Forest Pine Way",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            City = "Portland",
                            FullAddress = "910 Alpine Ridge Ave",
                            UserId = "user-cust-003"
                        },
                        new
                        {
                            Id = 4,
                            City = "Amman",
                            FullAddress = "Queen Rania St, Building 45",
                            UserId = "user-cust-004"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CampTravelGear.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CampTravelGear.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Bags & Pack"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Tent & Accessories"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Camp Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Knives & Tools"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Climbing & Hiking"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            CreatedAt = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            TotalAmount = 338.00m,
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            CreatedAt = new DateTime(2026, 8, 18, 9, 15, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 18, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Processing",
                            TotalAmount = 187.00m,
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            CreatedAt = new DateTime(2026, 8, 19, 16, 45, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 19, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            TotalAmount = 103.00m,
                            UserId = "user-cust-003"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            CreatedAt = new DateTime(2026, 8, 21, 11, 20, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 21, 11, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            TotalAmount = 217.00m,
                            UserId = "user-cust-004"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            CreatedAt = new DateTime(2026, 8, 23, 13, 10, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 23, 13, 10, 0, 0, DateTimeKind.Utc),
                            Status = "Processing",
                            TotalAmount = 171.00m,
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 2,
                            CreatedAt = new DateTime(2026, 8, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            OrderDate = new DateTime(2026, 8, 24, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            TotalAmount = 138.00m,
                            UserId = "user-cust-002"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 189.00m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 149.00m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 149.00m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 38.00m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 39.00m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 12,
                            Quantity = 1,
                            UnitPrice = 64.00m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 165.00m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 11,
                            Quantity = 1,
                            UnitPrice = 52.00m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 135.00m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 36.00m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            ProductId = 10,
                            Quantity = 1,
                            UnitPrice = 89.00m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 6,
                            ProductId = 8,
                            Quantity = 1,
                            UnitPrice = 49.00m
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 338.00m,
                            OrderId = 1,
                            PaidAt = new DateTime(2026, 8, 10, 14, 32, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            Status = "Completed",
                            TransactionId = "TXN-849201"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 187.00m,
                            OrderId = 2,
                            PaidAt = new DateTime(2026, 8, 18, 9, 16, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "PayPal",
                            Status = "Completed",
                            TransactionId = "TXN-739102"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 103.00m,
                            OrderId = 3,
                            PaymentMethod = "Credit Card",
                            Status = "Failed",
                            TransactionId = "TXN-109483"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 217.00m,
                            OrderId = 4,
                            PaidAt = new DateTime(2026, 8, 21, 11, 22, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Apple Pay",
                            Status = "Completed",
                            TransactionId = "TXN-559124"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 171.00m,
                            OrderId = 5,
                            PaymentMethod = "Cash on Delivery",
                            Status = "Pending",
                            TransactionId = "TXN-662391"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 138.00m,
                            OrderId = 6,
                            PaidAt = new DateTime(2026, 8, 24, 15, 5, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card",
                            Status = "Completed",
                            TransactionId = "TXN-773419"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engineered for rugged wilderness expeditions and weekend family getaways alike, the Rahhala Horizon 4-Person Tent delivers uncompromising storm protection and exceptional ventilation. Constructed from heavy-duty 210T ripstop polyester with a 3,500mm polyurethane waterproof coating, this tent keeps your camp completely dry even during continuous torrential downpours.\n\nThe freestanding geodesic frame uses 9.5mm aircraft-grade anodized aluminum poles that resist high mountain winds up to 60 km/h. Inside, dual oversized mesh doors and dual vestibules provide generous gear storage and cross-ventilation to prevent condensation. Features factory seam-taped bathtub floors, reflective guy lines, and internal organizer pockets for headlamps and maps.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rahhala Horizon 4-Person Geodesic Camping Tent",
                            Price = 189.00m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Built for multi-day alpine traverses and rugged backcountry journeys, the Alpine Apex 65L backpack combines maximum load stability with breathable trail ergonomics. The dynamic torso adjustment system fits heights from 5'4\" to 6'4\", transferring 80% of pack weight smoothly to the multi-density contoured hip belt.\n\nFabricated from 420D high-tenacity Cordura nylon with abrasion-resistant Hypalon reinforcement panels, this pack easily withstands jagged rock scrambles. Includes a dedicated sleeping bag bottom compartment with internal divider, integrated 3L hydration bladder sleeve, dual trekking pole attachments, and a stowable high-visibility waterproof rain cover.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Alpine Apex 65L Internal Frame Mountain Expedition Backpack",
                            Price = 149.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weighing merely 580 grams, the Rahhala Trekker Camp Stool is the ultimate lightweight seating solution for backpackers, trail runners, and campfire gatherings. Crafted with 7075 aviation-grade aluminum tubing with shock-corded assembly, it sets up in under 5 seconds and supports weights up to 130 kg (285 lbs).\n\nThe seat is woven from 600D water-repellent oxford canvas with reinforced bar-tack stitching at all stress points. Packs down into an ultra-compact cylinder that slips effortlessly into side water bottle pockets, making it an indispensable companion on every journey.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rahhala Trekker Ultra-Compact Aluminum Folding Camp Stool",
                            Price = 38.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engineered for alpine bivouacs and cold mountain nights, the GlacierPeak sleeping bag delivers premium 750-fill-power hydrophobic goose down insulation rated for temperatures down to -10°C (14°F). The anatomically curved mummy profile minimizes dead air space for instant thermal retention.\n\nFeatures a 20D DWR-treated micro-ripstop shell that sheds condensation, a full-length insulated draft tube along the anti-snag YKK two-way zipper, and an ergonomic 3D footbox. Compresses down to the size of a water bottle in the included waterproof compression dry sack.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "GlacierPeak -10°C Ultralight Goose Down Mummy Sleeping Bag",
                            Price = 165.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crafted from precision-machined aerospace titanium, this ultralight 48g backpacking stove boils 1 liter of water in just 3.2 minutes while consuming minimal isobutane fuel. The concave burner head creates a localized micro-tornado flame that resists gusts up to 30 km/h without requiring a bulky windscreen.\n\nFoldable serrated pot supports accommodate cookware from small 500ml titanium mugs to 2-liter camp pots. Fits standard threaded Lindal valve fuel canisters and folds neatly into an included protective hard-shell case for effortless packing.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TitanFlame Backcountry Micro Windproof Titanium Camp Stove",
                            Price = 42.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conquer demanding rocky terrains, mud trails, and mountain summits with confidence. The TerraGrip boots combine waterproof full-grain nubuck leather with breathable HydroGuard waterproof membrane booties that keep feet completely dry while releasing internal perspiration.\n\nEquipped with custom deep-lug Vibram Megagrip rubber outsoles for exceptional braking power on steep descents. An injected EVA midsole and thermoplastic shank absorb trail shock and protect feet from sharp jagged rocks throughout long trekking days.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TerraGrip Waterproof Ankle-Support Hiking Trail Boots",
                            Price = 135.00m,
                            Stock = 24
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light up your entire campsite with 360-degree diffused illumination. The Solaris Lantern outputs up to 1,200 lumens with 4 versatile lighting modes: Warm Campfire Glow, Cool Daylight, Red Night-Vision, and Emergency SOS Flashing.\n\nPowered by an internal 5,200mAh rechargeable lithium battery that provides up to 70 hours of continuous runtime on low mode and doubles as an emergency USB power bank to charge smartphones on the trail. Features an IPX6 waterproof rating, magnetic base, and top carabiner hook.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Solaris 1200-Lumen Rechargeable LED Camp Lantern & Power Bank",
                            Price = 39.00m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Precision crafted from heat-treated 440C stainless steel, this heavy-duty multi-tool integrates 14 essential backcountry tools: spring-loaded needle-nose pliers, wire cutters, wood saw, serrated blade, can opener, bottle opener, Phillips and flat screwdrivers, and a ruler.\n\nEvery individual implement securely locks in place with a safety lever to prevent accidental closure during intense cutting or sawing tasks. Includes a heavy-duty ballistic nylon belt sheath.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SwissForge 14-in-1 Tactical Stainless Outdoor Multi-Tool",
                            Price = 49.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keep hydration icy cold for 36 hours or soup steaming hot for 18 hours. The HydroShield Canteen is manufactured from food-grade 18/8 kitchen stainless steel with TempLock double-wall vacuum insulation that never transfers flavor or creates outer condensation.\n\nFeatures a wide mouth for adding ice cubes, a leakproof twist-lock cap with an integrated stainless carrying handle, and a durable powder-coat exterior finish that resists scuffs and trail drops.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "HydroShield Double-Wall Vacuum Insulated Camping Canteen 1.5L",
                            Price = 36.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Experience breathtaking clarity on wildlife spotting and trail reconnaissance. The ApexView features fully multi-coated FMC green broadband optics and premium BAK-4 roof prisms that deliver 99.5% light transmission even in low-light twilight conditions.\n\nO-ring sealed and nitrogen purged for 100% fogproof and waterproof performance in all climates. Rugged rubber armor absorbs shocks and provides a non-slip grip in wet weather. Includes neck strap, carrying case, and protective lens caps.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "ApexView 12x50 HD Waterproof Nitrogen-Purged Binoculars",
                            Price = 89.00m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Say goodbye to waking up on hard uneven ground. The CloudRest features 3 inches of high-density open-cell memory foam with an insulated R-value of 4.8, providing true 4-season thermal barrier from frozen ground.\n\nDual wide-mouth brass valves inflate the pad in under 60 seconds with zero pumping required. The top surface is soft-touch peached polyester that prevents sleeping bag rustle, while the bottom uses tough 75D puncture-resistant polyester with anti-slip silicone dots.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "CloudRest Self-Inflating 3-Inch Ergonomic Camp Sleeping Pad",
                            Price = 52.00m,
                            Stock = 32
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engineered with 100% 3K carbon fiber shafts, these trekking poles absorb trail vibrations and reduce knee strain by up to 25% on steep mountain descents. Weighs just 210 grams per pole.\n\nAluminum SpeedLock levers allow quick length adjustments from 65cm to 135cm even while wearing thick winter gloves. Features ergonomic natural cork grips that wick sweat, breathable padded wrist straps, carbide tungsten tips, and interchangeable mud and snow baskets.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "TrailFlow Quick-Lock Carbon Fiber Trekking Poles (Pair)",
                            Price = 64.00m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/Products/1/img_1.jpg",
                            IsMain = true,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/Products/1/img_2.jpg",
                            IsMain = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/Products/1/img_3.jpg",
                            IsMain = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/Products/1/img_4.jpg",
                            IsMain = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/Products/2/img_1.jpg",
                            IsMain = true,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "/images/Products/2/img_2.jpg",
                            IsMain = false,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "/images/Products/2/img_3.jpg",
                            IsMain = false,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "/images/Products/2/img_4.jpg",
                            IsMain = false,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "/images/Products/3/img_1.jpg",
                            IsMain = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "/images/Products/3/img_2.jpg",
                            IsMain = false,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "/images/Products/3/img_3.jpg",
                            IsMain = false,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "/images/Products/3/img_4.jpg",
                            IsMain = false,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "/images/Products/4/img_1.jpg",
                            IsMain = true,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "/images/Products/4/img_2.jpg",
                            IsMain = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "/images/Products/4/img_3.jpg",
                            IsMain = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "/images/Products/4/img_4.jpg",
                            IsMain = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "/images/Products/5/img_1.jpg",
                            IsMain = true,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "/images/Products/5/img_2.jpg",
                            IsMain = false,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "/images/Products/5/img_3.jpg",
                            IsMain = false,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "/images/Products/5/img_4.jpg",
                            IsMain = false,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "/images/Products/6/img_1.jpg",
                            IsMain = true,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "/images/Products/6/img_2.jpg",
                            IsMain = false,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "/images/Products/6/img_3.jpg",
                            IsMain = false,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "/images/Products/6/img_4.jpg",
                            IsMain = false,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "/images/Products/7/img_1.jpg",
                            IsMain = true,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "/images/Products/7/img_2.jpg",
                            IsMain = false,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "/images/Products/7/img_3.jpg",
                            IsMain = false,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "/images/Products/7/img_4.jpg",
                            IsMain = false,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "/images/Products/8/img_1.jpg",
                            IsMain = true,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "/images/Products/8/img_2.jpg",
                            IsMain = false,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "/images/Products/8/img_3.jpg",
                            IsMain = false,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "/images/Products/8/img_4.jpg",
                            IsMain = false,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "/images/Products/9/img_1.jpg",
                            IsMain = true,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "/images/Products/9/img_2.jpg",
                            IsMain = false,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "/images/Products/9/img_3.jpg",
                            IsMain = false,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "/images/Products/9/img_4.jpg",
                            IsMain = false,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "/images/Products/10/img_1.jpg",
                            IsMain = true,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "/images/Products/10/img_2.jpg",
                            IsMain = false,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "/images/Products/10/img_3.jpg",
                            IsMain = false,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "/images/Products/10/img_4.jpg",
                            IsMain = false,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "/images/Products/11/img_1.jpg",
                            IsMain = true,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "/images/Products/11/img_2.jpg",
                            IsMain = false,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 43,
                            ImageUrl = "/images/Products/11/img_3.jpg",
                            IsMain = false,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 44,
                            ImageUrl = "/images/Products/11/img_4.jpg",
                            IsMain = false,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 45,
                            ImageUrl = "/images/Products/12/img_1.jpg",
                            IsMain = true,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 46,
                            ImageUrl = "/images/Products/12/img_2.jpg",
                            IsMain = false,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 47,
                            ImageUrl = "/images/Products/12/img_3.jpg",
                            IsMain = false,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 48,
                            ImageUrl = "/images/Products/12/img_4.jpg",
                            IsMain = false,
                            ProductId = 12
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedAt = new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "Outstanding 4-person tent! Pitched it during heavy rain in the mountains and stayed bone dry. Setup took under 5 minutes.",
                            CreatedAt = new DateTime(2026, 8, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5,
                            Status = "Accepted",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 2,
                            ApprovedAt = new DateTime(2026, 8, 15, 15, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "The weight distribution on this 65L pack is incredible. The lumbar support saved my back on a 4-day ridge traverse.",
                            CreatedAt = new DateTime(2026, 8, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 5,
                            Status = "Accepted",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 3,
                            ApprovedAt = new DateTime(2026, 8, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "Surprisingly sturdy for how small it folds down. Fits right into the bottle pocket of my backpack.",
                            CreatedAt = new DateTime(2026, 8, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Rating = 4,
                            Status = "Accepted",
                            UserId = "user-cust-003"
                        },
                        new
                        {
                            Id = 4,
                            ApprovedAt = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "Super warm goose down sleeping bag for sub-zero mountain nights. Extremely compact when compressed.",
                            CreatedAt = new DateTime(2026, 8, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 4,
                            Rating = 5,
                            Status = "Accepted",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 5,
                            ApprovedAt = new DateTime(2026, 8, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            Comment = "Exceptional grip on rocky trails in Petra and Wadi Rum. Completely waterproof and comfortable all day.",
                            CreatedAt = new DateTime(2026, 8, 22, 16, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 6,
                            Rating = 5,
                            Status = "Accepted",
                            UserId = "user-cust-004"
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Terrific camp lantern. The warm campfire mode is great inside the tent and it charged my phone on the trail.",
                            CreatedAt = new DateTime(2026, 8, 23, 18, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 7,
                            Rating = 4,
                            Status = "Pending",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 7,
                            Comment = "The multi-tool is great quality, but the outer packaging was slightly squished during delivery.",
                            CreatedAt = new DateTime(2026, 8, 23, 19, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 8,
                            Rating = 2,
                            Status = "Rejected",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Crisp and clear BAK-4 optics for desert stargazing and mountain wildlife observation.",
                            CreatedAt = new DateTime(2026, 8, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 10,
                            Rating = 5,
                            Status = "Pending",
                            UserId = "user-cust-004"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovedAt = new DateTime(2026, 7, 21, 10, 0, 0, 0, DateTimeKind.Utc),
                            Content = "Rahhala gear survived our 10-day alpine trek in freezing storms. Best outdoor brand quality and fast delivery!",
                            CreatedAt = new DateTime(2026, 7, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sara G. Helvey",
                            Status = "Accepted",
                            UserId = "user-cust-002"
                        },
                        new
                        {
                            Id = 2,
                            ApprovedAt = new DateTime(2026, 7, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            Content = "The most reliable camping gear store I have ever used. Authentic rugged equipment and top customer support.",
                            CreatedAt = new DateTime(2026, 7, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Name = "John Doe",
                            Status = "Accepted",
                            UserId = "user-cust-001"
                        },
                        new
                        {
                            Id = 3,
                            ApprovedAt = new DateTime(2026, 7, 27, 16, 0, 0, 0, DateTimeKind.Utc),
                            Content = "The top outdoor camping outfitter in Jordan. Genuine technical gear and great customer care at their Amman center!",
                            CreatedAt = new DateTime(2026, 7, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Omar Al-Khalil",
                            Status = "Accepted",
                            UserId = "user-cust-004"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Their geodesic tents and titanium stoves are elite level. Highly recommended to any wilderness adventurer.",
                            CreatedAt = new DateTime(2026, 7, 28, 16, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Alex Hunter",
                            Status = "Pending",
                            UserId = "user-cust-003"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Visit this promotional third-party spam link for discounts.",
                            CreatedAt = new DateTime(2026, 7, 29, 8, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spam User",
                            Status = "Rejected",
                            UserId = "user-cust-001"
                        });
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("CampTravelGear.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-001",
                            ConcurrencyStamp = "role-admin-stamp",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "role-customer-002",
                            ConcurrencyStamp = "role-customer-stamp",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "user-admin-001",
                            RoleId = "role-admin-001"
                        },
                        new
                        {
                            UserId = "user-cust-001",
                            RoleId = "role-customer-002"
                        },
                        new
                        {
                            UserId = "user-cust-002",
                            RoleId = "role-customer-002"
                        },
                        new
                        {
                            UserId = "user-cust-003",
                            RoleId = "role-customer-002"
                        },
                        new
                        {
                            UserId = "user-cust-004",
                            RoleId = "role-customer-002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CampTravelGear.Models.Address", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.CartItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.HasOne("CampTravelGear.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.OrderItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Payment", b =>
                {
                    b.HasOne("CampTravelGear.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.HasOne("CampTravelGear.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CampTravelGear.Models.ProductImage", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CampTravelGear.Models.Review", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Testimonial", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampTravelGear.Models.WishlistItem", b =>
                {
                    b.HasOne("CampTravelGear.Models.Product", "Product")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistItems")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CampTravelGear.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CampTravelGear.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CampTravelGear.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CampTravelGear.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CampTravelGear.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("CampTravelGear.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
